name: personenregistrirungssystem
version: 0.1.0.0
github: "whole-white-whale/personenregistrirungssystem"
license: BSD-3-Clause
author: "Sergey Kirichenko"
maintainer: "whole-white-whale@yandex.ru"
copyright: "2024 Sergey Kirichenko"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/whole-white-whale/personenregistrirungssystem#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - postgresql-simple
  - servant-server
  - warp

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  personenregistrirungssystem-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - personenregistrirungssystem

tests:
  personenregistrirungssystem-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - personenregistrirungssystem
      - QuickCheck
