version: "3"
services:
  personenregistrirungssystem:
    image: "wholewhitewhale/personenregistrirungssystem:latest"
    restart: "on-failure"
    environment:
      CONNECTION_STRING: "postgresql://program:test@postgres/persons"
    ports:
      - "8080:8080"

  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  db-data:
